apiVersion: stoetti.github.com/v1
kind: CustomPod
metadata:
  name: test
  namespace: default
spec:
  podTemplate:
    spec:
      containers:
      - name: cont1
        env:
          - name: env1
            value: value1
