apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: custompods.stoetti.github.com
spec:
  group: stoetti.github.com
  names:
    kind: CustomPod
    plural: custompods
    singular: customerpod
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podTemplate:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
