apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - custom-pod-crd.yaml
  - custom-pod.yaml

openapi:
  path: openapi.json

patchesStrategicMerge:
  - |-
    apiVersion: stoetti.github.com/v1
    kind: CustomPod
    metadata:
      name: test
    spec:
      podTemplate:
        spec:
          containers:
            - name: cont1
              env:
                - name: env2
                  value: value2

